"""domain tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-03 03:47:44.183603

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('send_logs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('case_id', sa.String(length=26), nullable=False),
    sa.Column('rebuttal_id', sa.String(length=26), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('attachment_names', sa.JSON(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('send_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_send_logs_case_id'), ['case_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_user_id'), ['user_id'], unique=False)

    op.create_table('analyses',
    sa.Column('case_id', sa.String(length=26), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('case_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_case_id'), ['case_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('case_id', sa.String(length=26), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_case_id'), ['case_id'], unique=False)

    op.create_table('rebuttals',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('case_id', sa.String(length=26), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=True),
    sa.Column('claim_number', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('subject_auto', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('case_id', sa.String(length=26), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('caveat', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('revision_request', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_case_id'), ['case_id'], unique=False)

    op.create_table('verdicts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('case_id', sa.String(length=26), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('ratio_mine', sa.Integer(), nullable=False),
    sa.Column('ratio_other', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('opponent_claim', sa.JSON(), nullable=True),
    sa.Column('basis', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verdicts_case_id'), ['case_id'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('case_id', sa.String(length=26), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('report_pdfs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('report_id', sa.String(length=26), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_pdfs')
    op.drop_table('videos')
    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verdicts_case_id'))

    op.drop_table('verdicts')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_case_id'))

    op.drop_table('reports')
    op.drop_table('rebuttals')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_case_id'))

    op.drop_table('messages')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_case_id'))

    op.drop_table('jobs')
    op.drop_table('analyses')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_user_id'))

    op.drop_table('cases')
    with op.batch_alter_table('send_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_send_logs_case_id'))

    op.drop_table('send_logs')
    # ### end Alembic commands ###
